# **gh cli install for Github Runner:**
# Following steps need to be run manually as ec2-user
# sudo curl -L -o /etc/yum.repos.d/gh-cli.repo https://cli.github.com/packages/rpm/gh-cli.repo
# sudo dnf install gh -y
# gh auth login -s admin:org  (this particular command is not supporting end-to-end automation so we are doing it manually)

- name: Set Prompt
  ansible.builtin.shell: set-prompt {{ tool_name }}

- name: Add Github runner user
  ansible.builtin.user:
    name: github-runner

- name: Create runner directory
  ansible.builtin.file:
    path: /actions-runner
    state: directory
    owner: github-runner
    group: github-runner

- name: Download Runner
  ansible.builtin.unarchive:
    src: https://github.com/actions/runner/releases/download/v2.320.0/actions-runner-linux-x64-2.320.0.tar.gz
    dest: /actions-runner
    remote_src: yes
    owner: github-runner
    group: github-runner

- name: Install libicu
  ansible.builtin.dnf:
    name: libicu
    state: installed

- name: Get token
  ansible.builtin.shell: |
    gh api --method POST -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /orgs/tejadevsecops/actions/runners/registration-token | jq .token
  register: token
  become_user: ec2-user

- name: Register runner
  ansible.builtin.shell: |
    ./config.sh --unattended --url https://github.com/tejadevsecops --token {{ token.stdout }}  --name {{ ansible_hostname }} --runnergroup Default
  become_user: github-runner
  args:
    chdir: /actions-runner
  ignore_errors: yes

- name: Copy Service file
  ansible.builtin.copy:
    src: github-runner.service
    dest: /etc/systemd/system/github-runner.service

- name: Start Runner service
  ansible.builtin.systemd_service:
    name: github-runner
    daemon-reload: yes
    enabled: yes
    state: restarted

- name: Download terraform repo
  ansible.builtin.get_url:
    url: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
    dest: /etc/yum.repos.d/hashicorp.repo

- name: Install Terraform
  ansible.builtin.dnf:
    name: terraform
    state: installed

- name: Copy Kubernetes repo
  ansible.builtin.copy:
    src: kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo

- name: Install kubectl
  ansible.builtin.dnf:
    name: kubectl
    state: installed

- name: Install Docker
  ansible.builtin.shell: |
    curl -o /etc/yum.repos.d/docker.repo https://download.docker.com/linux/rhel/docker-ce.repo
    dnf install docker-ce --nobest -y
    usermod -a -G docker github-runner
    systemctl enable docker
    systemctl start docker

- name: LVN Layout
  ansible.builtin.include_role:
    name: common
    tasks_from: lvm

- name: Install ArgoCD Cli
  ansible.builtin.get_url:
    url: https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
    dest: /bin/argocd
    mode: '0755'