- name: Set Prompt
  tags:
    - elk
  ansible.builtin.shell: set-prompt {{ tool_name }}

- name: Copy Elastic repo file
  tags:
    - elk
  ansible.builtin.copy:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: LVN Layout
  tags:
    - elk
  ansible.builtin.include_role:
    name: common
    tasks_from: lvm

- name: Install ELK
  tags:
    - elk
  ansible.builtin.dnf:
    name:
      - elasticsearch
      - kibana
      - logstash
      - nginx
    state: installed

- name: Copy nginx config file
  tags:
    - elk
  ansible.builtin.copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Copy logstash
  tags:
    - elk
    - logstash
  ansible.builtin.template:
    src: logstash.conf
    dest: /etc/logstash/conf.d/logstash.conf

- name: Start ELK
  tags:
    - elk
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  loop:
    - elasticsearch
    - kibana
    - logstash
    - nginx

- name: Restart Logstash
  tags:
    - logstash
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  loop:
    - logstash





# Generate an enrollment token for Kibana instances with
#  /usr/share/elasticsearch/bin/elasticsearch-create-enrollment-token -s kibana
# Kibana Verification
# /usr/share/kibana/bin/kibana-verification-code
# Reset admin password
# /usr/share/elasticsearch/bin/elasticsearch-reset-password -u elastic